C:\Users\Admin\anaconda3\Lib\site-packages\pydantic\_internal\_config.py:373: UserWarning: Valid config keys have changed in V2:
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)
[32mINFO[0m:     Started server process [[36m23264[0m]
[32mINFO[0m:     Waiting for application startup.
